"""Initial

Revision ID: a24c1f89c87b
Revises: 
Create Date: 2024-01-11 23:48:50.976468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a24c1f89c87b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.schema.CreateSequence(sa.Sequence("message_id_seq")))
    op.execute(sa.schema.CreateSequence(sa.Sequence("session_id_seq")))
    op.create_table('message',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('message_id_seq')"), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('mc1_timestamp', sa.DateTime(), nullable=True),
    sa.Column('mc2_timestamp', sa.DateTime(), nullable=True),
    sa.Column('mc3_timestamp', sa.DateTime(), nullable=True),
    sa.Column('end_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    op.create_index(op.f('ix_message_session_id'), 'message', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_session_id'), table_name='message')
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.drop_table('message')
    # ### end Alembic commands ###
